### ISSUE TITLE
Remove other formats except SBOL

### ISSUE THREAD

**Issue by jvscholz** [VisBOL/visbol-site#2]
Remove tabs for Pigeon and GENBANK. We are only concerned with SBOL.

**Comment by jamesamcl** [comment]
Who’s only concerned with SBOL?

**Comment by jvscholz** [comment]
@cjmyers

**Comment by jamesamcl** [comment]
Veto

**Comment by cjmyers** [comment]
The tabs are pigeon and genbank. Do you really want to continue to maintain those? How are you doing Genbank? Are you using libsbolj somehow?

Chris

**Comment by jamesamcl** [comment]
GenBank is pretty limited as it is so I wouldn’t be particularly bothered if it was removed. It uses genbankjs.  

The wetlab people here who have used Visbol have all used pigeon syntax because it can be written by hand, so I would object to removing pigeon.

**Comment by cjmyers** [comment]
Ok fair enough 

Chris
